# -*- coding: utf-8 -*-
"""Tutoría Semana 12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bk3AaMaiIZYijFIBI8_e1W0dpEiFeaNC
"""

class String:
    def __init__(self, string=''):
        self.__string = string
    
    def __str__(self):
        return self.__string
    
    def getData(self):
        return self.__string

    def __add__(self, string2):
        if isinstance(string2, str):
            return String(self.__string + string2)
        elif isinstance(string2, String):
            return String(self.__string + string2.getData())
        else:
            return String(self.__string + str(string2))

    def find(self, elemento, inicio=0, fin=None):
        if fin == None:
            fin = len(self.__string) - 1
        
        indices = []

        for i in range(inicio, fin + 1):
            if self.__string[i] == elemento:
                indices.append(i)

        return indices

cadena = String('hola')
cadena2 = String(' mundo')
cadena3 = cadena + cadena2
print(cadena3)
print(cadena3.find('o'))
print(cadena3.find('!'))

"""# **Herencia**"""

# Clase padre
class Persona:
    def __init__(self, nombre, edad, cedula):
        self.nombre = nombre
        self.edad = edad
        self.cedula = cedula
    
    def __str__(self):
        return f'Nombre: {self.nombre}\nEdad: {self.edad}\nCedula: {self.cedula}'
    
    def saludar(self, nombre):
        return 'Hola ' + nombre

pErick = Persona('Erick Obregon', 22, 305070987)
print(pErick)
print(pErick.saludar('Andres'))

# Clase hijo
class Estudiante(Persona):
    def __init__(self, nombre, edad, cedula, carnet, carrera):
        #Persona.__init__(self, nombre, edad, cedula)
        super(Estudiante, self).__init__(nombre, edad, cedula)
        self.carnet = carnet
        self.carrera = carrera
    
    def __str__(self):
        return super(Estudiante, self).__str__() +\
            f'\nCarnet: {self.carnet}\nCarrera: {self.carrera}'
    
    def estudiar(self):
        return 'Estoy estudiando'

estudianteErick = Estudiante('Erick Obregon', 22, 305070987, 2016123157, 'Ing. en Computadores')
print(estudianteErick)
print(estudianteErick.saludar('Andres'))
print(estudianteErick.estudiar())
print(estudianteErick.nombre)

"""# **Herencia Múltiple**"""

class Padre:
    def __init__(self, colorDeOjos, tipoDeCabello):
        self.colorDeOjos = colorDeOjos
        self.tipoDeCabello = tipoDeCabello
        self.peso = 20
    
    def saludar(self):
        return 'Hola'

class Madre:
    def __init__(self, colorDeCabello, altura):
        self.colorDeCabello = colorDeCabello
        self.altura = altura
        self.peso = 30
    
    def despedirse(self):
        return 'Adios'

class Hijo(Madre, Padre):
    def __init__(self, colorDeOjos, tipoDeCabello, colorDeCabello, altura):
        Madre.__init__(self, colorDeCabello, altura)
        Padre.__init__(self, colorDeOjos, tipoDeCabello)

hijoErick = Hijo('Marron oscuro', 'Colochos', 'Negro', '1.84')
print(hijoErick.despedirse())
print(hijoErick.saludar())
print(hijoErick.colorDeOjos)
print(hijoErick.tipoDeCabello)
print(hijoErick.colorDeCabello)
print(hijoErick.altura)
print(hijoErick.peso)