# -*- coding: utf-8 -*-
"""Tutoría Semana 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wbFFx57qgj8Ev0Q_5DVTZNKTt5TUVqJM
"""

num1 = int(input('Num1: '))
num2 = int(input('Num2: '))
print(num1 + num2)

input('Ingrese algo: ')

nombre = input('Ingrese su nombre: ')
edad = int(input('Ingrese su edad: '))

print('Su nombre es ' + nombre + ' y su edad es ' + str(edad))

print('Su nombre es', nombre, 'y su edad es', edad)

print(f'Su nombre es {nombre} y su edad es {edad}')

print('Su nombre es {} y su edad es {}'.format(nombre, edad))

encontrado = True

if encontrado == True:
    print('Encontrado')

if encontrado:
    print('Encontrado')

i = 0

while i < 10:
    print(i)
    i += 1

print('Terminado')

i = 0
num = 0

while True:

    if i % 2 == 0:
        num += 1

    print('Me repito', i, num)
    i += 1

    if num == 10:
        break

print('Termine')

i = 0
num = 0

while i < 10:
    if i % 3 == 0:
        num += i
    
    if i % 4 == 0:
        num -= 1

    print(num, i)

    i+= 1

print('Termine', num)

i = 10

while i < 100:
    print(i)
    i -= 1

for i in range(10):
    print(i)

i = 10

for i in range(10):
    print(i)

cadena = "Erick los saluda"

for caracter in cadena:
    if caracter != " ":
        print(caracter, end="")
    else:
        print(2, end="")

lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

for num in lista:
    if num % 2 == 0:
        print(num, end="")
    else:
        print(-1, end="")

for i in range(10, 0, -2):
    print(i)

for i in range(11, -1, -3):
    print(i)

lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

print(lista[2:5])

print(lista[:4])

print(lista[7:])

print(lista[:])

print(lista[6:10000])

print(lista[::-1])

nombre = 'Erick'
print(nombre[::-1])

nombre[0] = 'e'

nombre = 'e' + nombre[1:]
nombre

num = 25
num = num + 10
print(num)

num = 25
num += 10
print(num)

cadena = 'Hola'
cadena = cadena + ' como esta?'
print(cadena)

cadena = 'Hola'
cadena += ' como esta?'
print(cadena)

opcion = input('Digite "si" para terminar: ')

if opcion.upper() == 'SI':
    print('Programa terminado..')
else:
    print('Programa continua...')

nombre = 'Erick Andres'
print(nombre.split(' '))

def sumar(num1, num2):
    suma = num1 + num2
    print(suma)
    return suma

def restar(suma):
    resta = suma - 10
    print(resta)

edad1 = 1
edad2 = 2

edad3 = sumar(edad1, edad2)
restar(edad3)

###########(5, 10)
def operar(num1, num2):
    if num1 > num2:
        return num1 - num2
    elif num1 < num2:
        return num1 + num2
    else:
        return num1 * num2

num1 = 10
num2 = 5

######operar(num2=10, num1=5)
print(operar(num2=num1, num1=num2))